name: create environment
on:
  workflow_dispatch:
  push:

permissions:
  actions: write
  contents: write

jobs:
  create_environment:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Script
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createOrUpdateEnvironment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment_name: 'new_environment'
            })

