name: verify environment
on:
  workflow_dispatch:
  push:

jobs:
  verify_environment:
    runs-on: ubuntu-latest
    env:
      context: ${{ toJSON(github) }}
      obj1: ${{ toJSON(runner) }}
      obj2: ${{ toJSON(secrets) }}
    steps:
      - name: verify environment exists
        run: | 
          echo $context
          echo $obj1
          echo $obj2
