name: verify environment
on:
  workflow_dispatch:
  push:

jobs:
  verify_environment:
    runs-on: ubuntu-latest
    env:
      context: ${{ toJSON(github) }}
    steps:
      - name: verify environment exists
        run: | 
          echo $context
          echo  ${{ toJSON(runner) }}
          echo ${{ toJSON(secrets) }}
