name: verify environment
on:
  workflow_dispatch:
  push:

jobs:
  verify_environment:
    runs-on: ubuntu-latest
    env:
      context: ${{ toJSON(github) }}
      runner: ${{ toJSON(runner) }}
      secrets: ${{ toJSON(secrets) }}
    steps:
      - name: verify environment exists
        run: | 
          echo $context
          echo $runner
          echo $secrets
