name: create environments
on:
  workflow_dispatch:
  push:

jobs:
  create_test_environment:
    runs-on: ubuntu-latest
    steps:
      - uses: ./actions/create-environment

  deploy_test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: deploy to test
        run: echo Deploying to test...
  deploy_to_stage:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: deploy to stage
        run: echo Deploying to stage...