name: verify environment
on:
  workflow_dispatch:
  push:

permissions: write-all

jobs:
  verify_environment:
    runs-on: ubuntu-latest
    env:
      context: ${{ toJSON(github) }}
      obj2: ${{ toJSON(secrets) }}
      GH_TOKEN: ${{ secrets.token}}
    steps:
      - name: Get environment
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/DavidSNE/actions1/environments
      - name: create environment
        run: |
          curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/DavidSNE/actions1/environments/prod -d '{"wait_timer":30,"prevent_self_review":false,"reviewers": [{"type":"User","reviewer":{"login":"DavidSNE","id":57226990,"node_id":"MDQ6VXNlcjU3MjI2OTkw","avatar_url":"https://avatars.githubusercontent.com/u/57226990?v=4","gravatar_id":"","url":"https://api.github.com/users/DavidSNE","html_url":"https://github.com/DavidSNE","followers_url":"https://api.github.com/users/DavidSNE/followers","following_url":"https://api.github.com/users/DavidSNE/following{/other_user}","gists_url":"https://api.github.com/users/DavidSNE/gists{/gist_id}","starred_url":"https://api.github.com/users/DavidSNE/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/DavidSNE/subscriptions","organizations_url":"https://api.github.com/users/DavidSNE/orgs","repos_url":"https://api.github.com/users/DavidSNE/repos","events_url":"https://api.github.com/users/DavidSNE/events{/privacy}","received_events_url":"https://api.github.com/users/DavidSNE/received_events","type":"User","site_admin":false}}]}]}'
          #curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/DavidSNE/actions1/environments/prod -d '{"wait_timer":30,"prevent_self_review":false,"reviewers":null}'
