name: verify environment
on:
  workflow_dispatch:
  push:

jobs:
  verify_environment:
    runs-on: ubuntu-latest
    env:
      context: ${{ toJSON(github) }}
      obj2: ${{ toJSON(secrets) }}
    steps:
      - name: verify environment exists
        run: |  
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/DavidSNE/actions1/environments
