name: create environments
on:
  workflow_dispatch:
  push:

permissions: write-all

jobs:
  deploy_test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: deploy to test
        run: echo Deploying to test...
  deploy_to_stage:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: deploy to stage
        run: echo Deploying to stage...
