name: create environments
on:
  workflow_dispatch:
  push:

permissions: write-all

jobs:
  create_test_environment:
    runs-on: ubuntu-latest
    steps:
      - uses: thijsvtol/create-environments@3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
          repo: ${{ github.repository }}
          environments: myenv


  deploy_test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: deploy to test
        run: echo Deploying to test...
  deploy_to_stage:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: deploy to stage
        run: echo Deploying to stage...
