name: verify environment
on:
  workflow_dispatch:
  push:

jobs:
  verify_environment:
    runs-on: ubuntu-latest
    env:
      context: ${{ toJSON(github) }}
      env: ${{ toJSON(env) }}
    steps:
      - name: verify environment exists
        run: | 
          echo $context
          echo $env
