name: use-workflow
on:
  push:
  workflow_dispatch:

jobs:
  use-workflow:
    uses: DavidSNE/actions2/.github/workflows/reusable-workflow.yml@master
  set-variable:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: set-version
        run:   gh variable set TEST_VAR --body "Set from workflow"