name: use-workflow
on:
  push:
  workflow_dispatch:

jobs:
  use-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: call workflow
        uses: DavidSNE/actions2/actions/workflows/reusable-workflow.yml@master